### ISSUE TITLE
First time open app get force close because adapter is null pointer

### ISSUE THREAD

**Issue by kurorido** [Suleiman19/Android-Note-app-with-Sugar-ORM#1]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.grafixartist.noteapp.NotesAdapter.SetOnItemClickListener(com.grafixartist.noteapp.NotesAdapter$OnItemClickListener)' on a null object reference at com.grafixartist.noteapp.MainActivity.onCreate(MainActivity.java:138)
at android.app.Activity.performCreate(Activity.java:6033)

**Comment by daeynasvistas** [comment]
the same

**Comment by yonatanmekuriaw18** [comment]
the same

**Comment by Kokrra** [comment]
Any solution to this error please inform.

   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.grafixartist.noteapp.NotesAdapter.SetOnItemClickListener(com.grafixartist.noteapp.NotesAdapter$OnItemClickListener)' on a null object reference
                                                                              at com.grafixartist.noteapp.MainActivity.onCreate(MainActivity.java:137)

**Comment by kurorido** [comment]
Solution is really easy...

Nullpointer is cause by adapter does not initialize.

see the following code in MainActivitiy.java

> ```
>     if (initialCount >= 0) {
> 
>         notes = Note.listAll(Note.class);
> 
>         adapter = new NotesAdapter(MainActivity.this, notes);
>         recyclerView.setAdapter(adapter);
> 
>         if (notes.isEmpty())
>             Snackbar.make(recyclerView, "No notes added.", Snackbar.LENGTH_LONG).show();
> 
>     }
> ```

just add else statement to initialize adpater correctly.

for example: 

```
else {
 notes = new ArrayList<>();
 adapter = new NotesAdapter(MainActivity.this, notes);
}
```

**Comment by Kokrra** [comment]
I  did that but there is another error that makes app crash while opening.

   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.grafixartist.noteapp.NotesAdapter.SetOnItemClickListener(com.grafixartist.noteapp.NotesAdapter$OnItemClickListener)' on a null object reference
                                                                              at com.grafixartist.noteapp.MainActivity.onCreate(MainActivity.java:141)

Line 141 which starts from:

**Comment by Kokrra** [comment]
adapter.SetOnItemClickListener(new NotesAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {

```
            Log.d("Main", "click");

            Intent i = new Intent(MainActivity.this, AddNoteActivity.class);
            i.putExtra("isEditing", true);
            i.putExtra("note_title", notes.get(position).title);
            i.putExtra("note", notes.get(position).note);
            i.putExtra("note_time", notes.get(position).time);

            modifyPos = position;

            startActivity(i);
        }
    });`
```
